### ISSUE TITLE
composer install successful, magento 2.4.1 upgrade error

### ISSUE THREAD

**Issue by atiteam** [bigfish-hu/payment-gateway-module-magento2#1]
error message:
PHP Fatal error:  Uncaught Error: Class 'Magento\Braintree\Model\Paypal\Helper\AbstractHelper' not found in /var/www/shop.com/app/code/Bigfishpaymentgateway/Pmgw/Gateway/Helper/Helper.php:36

Stack trace:
#0 /var/www/shop.com/vendor/composer/ClassLoader.php(444): include()
#1 /var/www/shop.com/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/shop.com/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists()
#5 /var/www/shop.com/vendor/magento/framework/Interception/Config/Config.php(157): Magento\Framework\ObjectManager\Relations\Runtime->has()
#6 /var/www/shop.com/vendor/magento/framework/Interception/Config/Config.php(180): Magento\Framework\Interception\Config\Config->_inheritInterception()
#7 /var/www/shop.com/vendor/magento/framework/Interception/Config/Config.php(213): Magento\Frame in /var/www/shop.com/app/code/Bigfishpaymentgateway/Pmgw/Gateway/Helper/Helper.php on line 36

**Comment by viderspan** [comment]
We fixed the bug in the release below:

https://github.com/bigfish-hu/payment-gateway-module-magento2/releases/tag/3.2.2
